const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');const {spawnSync}=require('node:child_process');
const root=path.join(__dirname,'..');
const fresh=()=>{delete require.cache[require.resolve('../src/services/accessGate')];return require('../src/services/accessGate')};
test('gate kosong/off tidak melakukan API Telegram',async()=>{process.env.ACCESS_GATE_MODE='';let calls=0;const g=fresh();const r=await g.checkAccess({telegram:{getChatMember:async()=>{calls++}},user:{id:991001}});assert.equal(r.allowed,true);assert.equal(calls,0)});
test('mode join cek target aktif lalu cache 60 detik',async()=>{process.env.ACCESS_GATE_MODE='join';process.env.REQUIRED_CHANNEL_ID='-1001';process.env.REQUIRED_CHANNEL_URL='https://t.me/test';process.env.REQUIRED_GROUP_ID='';process.env.REQUIRED_GROUP_URL='';let calls=0;const g=fresh();const telegram={getChatMember:async()=>{calls++;return{status:'member'}}};assert.equal((await g.checkAccess({telegram,user:{id:991002}})).allowed,true);assert.equal((await g.checkAccess({telegram,user:{id:991002}})).allowed,true);assert.equal(calls,1);delete process.env.ACCESS_GATE_MODE});
test('mode join tanpa pasangan ID+URL gagal aman',async()=>{process.env.ACCESS_GATE_MODE='join';process.env.REQUIRED_CHANNEL_ID='-1001';process.env.REQUIRED_CHANNEL_URL='';const g=fresh();const r=await g.checkAccess({telegram:{},user:{id:991003}});assert.equal(r.allowed,false);assert.equal(r.configError,true);delete process.env.ACCESS_GATE_MODE});
test('migration additive approval bekerja pada DB lama',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'gate-'));fs.mkdirSync(path.join(dir,'src/models'),{recursive:true});fs.mkdirSync(path.join(dir,'src/database'),{recursive:true});fs.copyFileSync(path.join(root,'src/models/db.js'),path.join(dir,'src/models/db.js'));const script=`const db=require('./src/models/db');let r=db.requestAccess({id:'U1',first_name:'Buyer',username:'buyer'});db.decideAccess('U1','approved','A1');r=db.getAccessRequest('U1');console.log(JSON.stringify(r));`;const p=spawnSync(process.execPath,['-e',script],{cwd:dir,encoding:'utf8',env:{...process.env,NODE_PATH:path.join(root,'node_modules')}});assert.equal(p.status,0,p.stderr);const r=JSON.parse(p.stdout.trim().split('\n').at(-1));assert.equal(r.status,'approved');assert.equal(r.decided_by,'A1');fs.rmSync(dir,{recursive:true,force:true})});
test('middleware terpasang sebelum seluruh buyer handlers dan env default terdokumentasi',()=>{const index=fs.readFileSync(path.join(root,'src/index.js'),'utf8'),env=fs.readFileSync(path.join(root,'.env.example'),'utf8');assert.ok(index.indexOf('bot.use(accessGateMiddleware)')<index.indexOf('registerStartHandler(bot)'));for(const key of ['ACCESS_GATE_MODE=','REQUIRED_CHANNEL_ID=','REQUIRED_CHANNEL_URL=','REQUIRED_GROUP_ID=','REQUIRED_GROUP_URL='])assert.match(env,new RegExp(key))});
process.on('exit',()=>{for(const k of ['ACCESS_GATE_MODE','REQUIRED_CHANNEL_ID','REQUIRED_CHANNEL_URL','REQUIRED_GROUP_ID','REQUIRED_GROUP_URL'])delete process.env[k]});
