import { useEffect, useState, useCallback } from 'react';
import { fetchSettings, changeAdminPassword, downloadBackup, clearToken } from '../api.js';
import { useNavigate } from 'react-router-dom';
import Icon from '../components/Icons.jsx';
import './settings/settings.css';

const TABS=[{key:'security',label:'Keamanan',icon:'shield'},{key:'backup',label:'Backup',icon:'download'},{key:'system',label:'Info Sistem',icon:'terminal'}];
const strength=v=>{let n=0;if(v.length>=6)n++;if(v.length>=10)n++;if(/[A-Z]/.test(v)&&/[a-z]/.test(v))n++;if(/\d/.test(v)&&/[^A-Za-z0-9]/.test(v))n++;return n};

export default function Settings(){
 const navigate=useNavigate(),[tab,setTab]=useState('security'),[data,setData]=useState(null),[error,setError]=useState(''),[toast,setToast]=useState(null);
 const showToast=(msg,kind='ok')=>{setToast({msg,kind});setTimeout(()=>setToast(null),3200)};
 const load=useCallback(()=>fetchSettings().then(d=>{setData(d);setError('')}).catch(e=>setError(e.message)),[]);
 useEffect(()=>{load()},[load]);useEffect(()=>{const f=()=>load();window.addEventListener('settings_updated',f);return()=>window.removeEventListener('settings_updated',f)},[load]);
 if(error)return <div className="panel error-panel hint-icon"><Icon name="warning" size={16}/>{error}</div>;
 return <div className="settings-page settings-system-page"><div className="page-head"><div><h2 className="page-title">Settings</h2><p className="page-sub">Keamanan panel, backup database, dan informasi deployment</p></div></div><div className="settings-tabs system-settings-tabs">{TABS.map(t=><button key={t.key} className={`settings-tab ${tab===t.key?'active':''}`} onClick={()=>setTab(t.key)}><Icon name={t.icon} size={16}/><span>{t.label}</span></button>)}</div>{!data?<div className="panel"><div className="empty">Memuat pengaturan…</div></div>:tab==='security'?<SecurityTab data={data} showToast={showToast} onRelogin={()=>{clearToken();navigate('/login',{replace:true})}}/>:tab==='backup'?<BackupTab showToast={showToast}/>:<SystemTab env={data.env}/>} {toast&&<div className={`toast ${toast.kind}`}>{toast.msg}</div>}</div>;
}

function SecurityTab({data,showToast,onRelogin}){
 const[cur,setCur]=useState(''),[next,setNext]=useState(''),[confirm,setConfirm]=useState(''),[busy,setBusy]=useState(false),[show,setShow]=useState(false),score=strength(next),match=!!confirm&&next===confirm;
 const submit=async()=>{if(!cur)return showToast('Masukkan password lama','err');if(next.length<6)return showToast('Password baru minimal 6 karakter','err');if(next!==confirm)return showToast('Konfirmasi password tidak cocok','err');setBusy(true);try{const r=await changeAdminPassword(cur,next);showToast(r.message);setCur('');setNext('');setConfirm('');setTimeout(onRelogin,900)}catch(e){showToast(e.message,'err')}finally{setBusy(false)}};
 return <div className="security-layout"><section className="panel security-overview"><div className="settings-section-head"><span className="settings-icon"><Icon name="shield" size={20}/></span><div><h3>Keamanan Panel</h3><p>Status autentikasi dan sesi administrator.</p></div></div><div className="security-cards"><div><span>Sumber Password</span><b>{data.security.password_source==='custom'?'Database (scrypt)':'Environment (.env)'}</b><small>{data.security.password_source==='custom'?'Hash custom aktif':'Disarankan ganti dari panel'}</small></div><div><span>Durasi Sesi</span><b>{data.security.session_duration}</b><small>JWT administrator</small></div><div><span>JWT Secret</span><b>{data.security.jwt_source==='env'?'.env':'Database otomatis'}</b><small>Nilai rahasia tidak ditampilkan</small></div></div><div className="settings-safe-note"><Icon name="check" size={16}/><span>Setelah password diganti, seluruh sesi lama langsung dicabut dan Anda harus login ulang.</span></div></section><section className="panel password-panel"><div className="settings-section-head compact"><div><h3>Ganti Password</h3><p>Gunakan password unik khusus panel admin.</p></div><button className={`password-visibility ${show?'is-visible':'is-hidden'}`} onClick={()=>setShow(v=>!v)} aria-pressed={show} title={show?'Password sedang terlihat':'Password sedang disembunyikan'}><Icon name={show?'eye':'eye-off'} size={15}/><span>{show?'Terlihat':'Tersembunyi'}</span></button></div><div className="password-form"><label><span>Password Lama</span><input type={show?'text':'password'} className="qty-field" value={cur} onChange={e=>setCur(e.target.value)} autoComplete="current-password"/></label><label><span>Password Baru</span><input type={show?'text':'password'} className="qty-field" value={next} onChange={e=>setNext(e.target.value)} autoComplete="new-password"/><div className="strength"><i className={score>=1?'on':''}/><i className={score>=2?'on':''}/><i className={score>=3?'on':''}/><i className={score>=4?'on':''}/><small>{!next?'Minimal 6 karakter':score<=1?'Lemah':score===2?'Cukup':score===3?'Kuat':'Sangat kuat'}</small></div></label><label><span>Konfirmasi Password</span><input type={show?'text':'password'} className={`qty-field ${confirm&&!match?'input-error':''}`} value={confirm} onChange={e=>setConfirm(e.target.value)} autoComplete="new-password"/>{confirm&&<small className={match?'match-ok':'match-err'}>{match?'Password cocok':'Password belum cocok'}</small>}</label><button className="btn-primary" onClick={submit} disabled={busy||!cur||next.length<6||!match}>{busy?'Menyimpan…':'Ganti Password'}</button></div></section></div>;
}

function BackupTab({showToast}){const[downloading,setDownloading]=useState(false);const run=async()=>{setDownloading(true);try{await downloadBackup();showToast('Backup database berhasil diunduh')}catch(e){showToast(e.message,'err')}finally{setDownloading(false)}};return <div className="backup-layout"><section className="panel backup-main"><div className="backup-hero"><span><Icon name="download" size={28}/></span><div><h3>Snapshot Database</h3><p>Unduh snapshot SQLite konsisten saat bot tetap berjalan.</p></div></div><div className="backup-contains"><b>Termasuk di dalam backup</b><div><span>Order & pembayaran</span><span>Customer & saldo</span><span>Produk & stok</span><span>Voucher & pengaturan</span><span>Audit admin</span><span>Credential gateway terenkripsi DB</span></div></div><button className="btn-primary btn-icon backup-download" onClick={run} disabled={downloading}><Icon name="download" size={16}/>{downloading?'Menyiapkan snapshot…':'Unduh Backup Database'}</button></section><aside className="panel backup-warning"><Icon name="warning" size={20}/><div><h3>File Sensitif</h3><p>Backup berisi data operasional, hash password, dan credential gateway. Simpan offline atau di storage terenkripsi.</p><ul><li>Jangan kirim melalui grup publik</li><li>Batasi akses hanya untuk administrator</li><li>Buat backup rutin sebelum perubahan besar</li></ul></div></aside></div>}

function SystemTab({env}){const runtime=[['Admin Telegram ID',env.admin_id,'ADMIN_ID'],['Port Server',env.port,'PORT'],['Webhook URL Publik',env.webhook_url,'WEBHOOK_URL']],security=[['Bot Token',env.bot_token,'BOT_TOKEN',true],['JWT Secret',env.admin_jwt_secret,`Sumber: ${env.admin_jwt_source}`,true],['Password Login',env.admin_password_source,'Sumber aktif'],['Durasi Sesi','24 jam','JWT expiry']];return <div className="system-layout"><SystemGroup title="Runtime & Deployment" icon="terminal" rows={runtime}/><SystemGroup title="Security Runtime" icon="shield" rows={security}/><div className="settings-readonly-note"><Icon name="warning" size={16}/><span>Informasi ini read-only. Ubah konfigurasi deployment melalui <code>.env</code>, lalu restart bot jika diperlukan.</span></div></div>}
function SystemGroup({title,icon,rows}){return <section className="panel system-group"><div className="settings-section-head compact"><span className="settings-icon"><Icon name={icon} size={18}/></span><div><h3>{title}</h3></div></div><div className="sysinfo-list">{rows.map(([label,value,key,masked])=><div key={label} className="sysinfo-row"><div className="sysinfo-label">{label}<span className="sysinfo-key">{key}</span></div><div className="sysinfo-value mono">{value!=null&&value!==''?value:<span className="muted">— belum diset</span>}{masked&&value&&<span className="sysinfo-masked-badge">masked</span>}</div></div>)}</div></section>}
